### ISSUE TITLE
Error when retrieving HMDB0014328 & HMDB0060475

### ISSUE THREAD

**Issue by gmhhope** [vjcitn/hmdbQuery#4]
Dear Dr. Carey,

I encountered error when using your R package `hmdbQuery`
```
Error in validObject(.Object) : 
  invalid class “HmdbEntry” object: 1: invalid object for slot "diseases" in class "HmdbEntry": got class "NULL", should be or extend class "matrix"
invalid class “HmdbEntry” object: 2: invalid object for slot "biospecimens" in class "HmdbEntry": got class "NULL", should be or extend class "character"
The HMDB XML has an unexpected structure.  Please 
report the HMDB ID to stvjc@channing.harvard.edu.  Returning a list of all 
retrieved data.[1] "HMDB0014328"
Error in validObject(.Object) : 
  invalid class “HmdbEntry” object: invalid object for slot "diseases" in class "HmdbEntry": got class "NULL", should be or extend class "matrix"
The HMDB XML has an unexpected structure.  Please 
report the HMDB ID to stvjc@channing.harvard.edu.  Returning a list of all 
retrieved data.[1] "HMDB0060475"
```

But actually, the list object is great for retrieving other related information (e.g., molecular weight, monoisotopic mass). Is your package equipped to have the full list object, instead of S4 object retrieved?

I appreciate your help!

Thanks,
Minghao Gong

**Comment by gmhhope** [comment]
I just found your code which has function to parse that `hmxToList`. You can close this issue. 

Thanks,
Minghao

**Comment by vjcitn** [comment]
Thanks for your note.  I would comment that the hmxToList is not exported by the package.
But maybe it should be.  If you have any time to submit a pull request, you could make the
changes to export it, or, better, modify HmdbEntry so that it does not fail in this situation.
I will try to do it eventually but I have very little time.  I would be glad to include you as
an author of the package should you make such a pull request.

**Comment by gmhhope** [comment]
> Thanks for your note. I would comment that the hmxToList is not exported by the package.
> But maybe it should be. If you have any time to submit a pull request, you could make the
> changes to export it, or, better, modify HmdbEntry so that it does not fail in this situation.
> I will try to do it eventually but I have very little time. I would be glad to include you as
> an author of the package should you make such a pull request.

Thanks for your suggestion and offer! 

I will try to find a good time to do so if I can, will let you know and do a pull request when I am ready!

Have a nice weekend!

Best,
Minghao Gong

**Comment by JianFelixGuo** [comment]
> > Thanks for your note. I would comment that the hmxToList is not exported by the package.
> > But maybe it should be. If you have any time to submit a pull request, you could make the
> > changes to export it, or, better, modify HmdbEntry so that it does not fail in this situation.
> > I will try to do it eventually but I have very little time. I would be glad to include you as
> > an author of the package should you make such a pull request.
> 
> Thanks for your suggestion and offer!
> 
> I will try to find a good time to do so if I can, will let you know and do a pull request when I am ready!
> 
> Have a nice weekend!
> 
> Best, Minghao Gong

Hi Minghao, I also had the same error messages. Could you please share with me how you solved the problem? Thank you!
